#! /usr/bin/env bash

pnpm local

cleanup() {
  pnpm remove @simplyhexagonal/logger-cli
  exit 1
}

pnpm logger.config $(pwd)/logger.mock.config.js \
  && pnpm logger.debug This is a debug message \
  && pnpm logger.info This message goes to Discord \
  && pnpm logger.warn This is a warn message \
  && pnpm logger.error This is a error message \
  && pnpm logger.fatal This is a fatal message \
  && uname -a | pnpm logger.all \
  && pnpm logger.raw This is a raw message \
  || cleanup

pnpm remove @simplyhexagonal/logger-cli
