name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests1:
    name: Test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Test
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: pnpm test
  tests2:
    name: Test on Node ${{ matrix.node }} and ${{ matrix.os }}
    needs: tests1

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Test
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: pnpm test
  tests3:
    name: Test on Node ${{ matrix.node }} and ${{ matrix.os }}
    needs: tests2

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Test
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: pnpm test
  tests4:
    name: Test on Node ${{ matrix.node }} and ${{ matrix.os }}
    needs: tests3

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x']
        os: [macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Test
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: pnpm test
